export const products = [
    { name: 'Apple', image: 'images/apple.jpg', category: 'fruits', price: 100 },
    { name: 'Banana', image: 'images/banana.jpg', category: 'fruits', price: 50 },
    { name: 'Carrot', image: 'images/carrot.jpg', category: 'vegetables', price: 40 },
    { name: 'Tomato', image: 'images/tomato.jpg', category: 'vegetables', price: 30 },
    { name: 'Potato', image: 'images/potato.jpg', category: 'vegetables', price: 20 },
    { name: 'Almonds', image: 'images/almonds.jpg', category: 'nuts', price: 150 },
    { name: 'Cashews', image: 'images/cashews.jpg', category: 'nuts', price: 200 },
    { name: 'Mango', image: 'images/mango.jpg', category: 'fruits', price: 120 },
    { name: 'Onion', image: 'images/onion.jpg', category: 'vegetables', price: 25 },
    { name: 'Strawberry', image: 'images/strawberry.jpg', category: 'fruits', price: 300 },
    { name: 'Pineapple', image: 'images/pineapple.jpg', category: 'fruits', price: 150 },
    { name: 'Walnuts', image: 'images/walnuts.jpg', category: 'nuts', price: 250 },
    { name: 'Watermelon', image: 'images/watermelon.jpg', category: 'fruits', price: 60 },
    { name: 'Cucumber', image: 'images/cucumber.jpg', category: 'vegetables', price: 30 },
    { name: 'Spinach', image: 'images/spinach.jpg', category: 'vegetables', price: 20 },
    { name: 'Pomegranate', image: 'images/pomegranate.jpg', category: 'fruits', price: 120 },
    { name: 'Lettuce', image: 'images/lettuce.jpg', category: 'vegetables', price: 50 },
    { name: 'Peanuts', image: 'images/peanuts.jpg', category: 'nuts', price: 100 },
    { name: 'Chilies', image: 'images/chilies.jpg', category: 'vegetables', price: 40 },
    { name: 'Blueberries', image: 'images/blueberries.jpg', category: 'fruits', price: 400 },
    { name: 'Avocado', image: 'images/avocado.jpg', category: 'fruits', price: 150 },
    { name: 'Broccoli', image: 'images/broccoli.jpg', category: 'vegetables', price: 60 },
    { name: 'Garlic', image: 'images/garlic.jpg', category: 'vegetables', price: 25 },
    { name: 'Raisins', image: 'images/raisins.jpg', category: 'nuts', price: 180 },
    { name: 'Sweet Corn', image: 'images/sweetcorn.jpg', category: 'vegetables', price: 50 },
    //new
    //dal
    { name: 'chana_dal', image: 'img/products/dal/chana_dal.webp', category: 'dal', price: 50 },
    { name: 'green_moong', image: 'img/products/dal/green_moong.webp', category: 'dal', price: 50 },
    { name: 'kali_masoor', image: 'img/products/dal/kali_masoor.webp', category: 'dal', price: 50 },
    { name: 'masoor_dal', image: 'img/products/dal/masoor_dal.webp', category: 'dal', price: 50 },
    { name: 'masoor_whole', image: 'img/products/dal/masoor_whole.webp', category: 'dal', price: 50 },
    { name: 'moong_dal', image: 'img/products/dal/moong_dal.webp', category: 'dal', price: 50 },
    { name: 'toor_dal', image: 'img/products/dal/toor_dal.webp', category: 'dal', price: 50 },
    { name: 'urad_dal', image: 'img/products/dal/urad_dal.webp', category: 'dal', price: 50 },
    { name: 'urad_kali', image: 'img/products/dal/urad_kali.webp', category: 'dal', price: 50 },
    { name: 'urad_whole', image: 'img/products/dal/urad_whole.webp', category: 'dal', price: 50 },
    //flour
    { name: 'besan', image: 'img/products/flour/besan.webp', category: 'flour', price: 50 },
    { name: 'ragi_atta', image: 'img/products/flour/ragi_atta.webp', category: 'flour', price: 50 },
    //masala
    { name: 'chaat_masala', image: 'img/products/masala/chaat_masala.webp', category: 'masala', price: 50 },
    { name: 'chicken_masala', image: 'img/products/masala/chicken_masala.webp', category: 'masala', price: 50 },
    { name: 'dal_tadka_masala', image: 'img/products/masala/dal_tadka_masala.webp', category: 'masala', price: 50 },
    { name: 'garam_masala', image: 'img/products/masala/garam_masala.webp', category: 'masala', price: 50 },
    { name: 'kitchen_king_masala', image: 'img/products/masala/kitchen_king_masala.webp', category: 'masala', price: 50 },
    { name: 'meat_masala', image: 'img/products/masala/meat_masala.webp', category: 'masala', price: 50 },
    { name: 'paneer_masala', image: 'img/products/masala/paneer_masala.webp', category: 'masala', price: 50 },
    { name: 'pav_bhaji_masala', image: 'img/products/masala/pav_bhaji_masala.webp', category: 'masala', price: 50 },
    { name: 'punjabi_chhole_masala', image: 'img/products/masala/punjabi_chhole_masala.webp', category: 'masala', price: 50 },
    { name: 'sambar_masala', image: 'img/products/masala/sambar_masala.webp', category: 'masala', price: 50 },
    //oil
    { name: 'cold_pressed_groundnut_oil', image: 'img/products/oil/cold_pressed_groundnut_oil.webp', category: 'oil', price: 50 },
    { name: 'cold_pressed_mustard_oil', image: 'img/products/oil/cold_pressed_mustard_oil.webp', category: 'oil', price: 50 },
    { name: 'cold_pressed_sesame_oil', image: 'img/products/oil/cold_pressed_sesame_oil.webp', category: 'oil', price: 50 },
    { name: 'cold_pressed_sunflower_oil', image: 'img/products/oil/cold_pressed_sunflower_oil.webp', category: 'oil', price: 50 },
    { name: 'groundnut_oil_organic', image: 'img/products/oil/groundnut_oil_organic.webp', category: 'oil', price: 50 },
    { name: 'mustard_oil_organic', image: 'img/products/oil/mustard_oil_organic.webp', category: 'oil', price: 50 },
    { name: 'virgin_coconut_oil_cold_pressed', image: 'img/products/oil/virgin_coconut_oil_cold_pressed.webp', category: 'oil', price: 50 },
    { name: 'virgin_coconut_oil_organic', image: 'img/products/oil/virgin_coconut_oil_organic.webp', category: 'oil', price: 50 },

    //poha
    { name: 'high_fibre_poha', image: 'img/products/poha/high_fibre_poha.webp', category: 'poha', price: 50 },
    { name: 'poha', image: 'img/products/poha/poha.webp', category: 'poha', price: 50 },
    //saffron
    { name: 'golden_saffron', image: 'img/products/saffron/golden_saffron.webp', category: 'saffron', price: 50 },
    //salt
    { name: 'rock_salt', image: 'img/products/salt/rock_salt.webp', category: 'salt', price: 50 },
    { name: 'tata_salt_himalayan', image: 'img/products/salt/tata_salt_himalayan.webp', category: 'salt', price: 50 },
    { name: 'tata_salt_iron_health', image: 'img/products/salt/tata_salt_iron_health.webp', category: 'salt', price: 50 },
    { name: 'tata_salt', image: 'img/products/salt/tata_salt.webp', category: 'salt', price: 50 },
    //spice
    { name: 'chilli_powder', image: 'img/products/spice/chilli_powder.webp', category: 'spice', price: 50 },
    { name: 'coriander_powder', image: 'img/products/spice/coriander_powder.webp', category: 'spice', price: 50 },
    { name: 'turmeric_powder', image: 'img/products/spice/turmeric_powder.webp', category: 'spice', price: 50 },
    //whole spice
    { name: 'black_pepper', image: 'img/products/whole_spice/black_pepper.webp', category: 'whole_spice', price: 50 },
    { name: 'cardamom_seed', image: 'img/products/whole_spice/cardamom_seed.webp', category: 'whole_spice', price: 50 },
    { name: 'coriander_seed', image: 'img/products/whole_spice/coriander_seed.webp', category: 'whole_spice', price: 50 },
    { name: 'cumin_seed', image: 'img/products/whole_spice/cumin_seed.webp', category: 'whole_spice', price: 50 },
    { name: 'fennel_seed', image: 'img/products/whole_spice/fennel_seed.webp', category: 'whole_spice', price: 50 },
    { name: 'ginger_garlic_paste', image: 'img/products/ginger_garlic_paste.webp', category: 'whole_spice', price: 50 },

];
<!-- <script src="https://unpkg.com/@tailwindcss/browser@4"></script> -->